# Generated by Django 5.2.17 on 2026-09-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_application_applicant_application_applied_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='last_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
